### PR TITLE
Fix xcontrol on xplane 12

### PR DESCRIPTION
**Pull request by murtas**
Xcontrol crashes during initialization on xplane 12, tested on linux. 

After upgrading SDK version and building it works without a problem.

### CODE REVIEW

**Comment by user2684** [comment]
Uau, this is amazing, thanks a lot for the huge contribution and for making this plugin progressing by a decade at last with a single PR :-)  
I just have a minor request. Could you also please advancing the version from 1.0.1 to 1.1.0 or something like that in main.cpp, out_saitek.cpp and add a line in the CHANGELOG file? So to distinguish between the old and new version :-) Then I will merge the PR. Really really appreciated

**Comment by murtas** [comment]
@user2684 I created v1.1.0 and introduced a changelog in line with your suggestion.

I also compiled the plugin for Linux (64 bit) and Mac (32/64 bit). 
Unfortunately I'm not being able to compile 32bit version on Linux not even the previous version v1.0.1.

I think we may consider dropping support for 32bit versions given the new plugin release targets X-Plane 12. What you think?

Meanwhile are you able to help building the plugin on Windows? I'll try to work on it next week, but I would appreciate your help if possible.

**Comment by user2684** [comment]
Hi, thank you SO much :-) Merging the pull request. Definitely, it has no sense to strictly support 32 bits these days so let's drop it whenever not available. Unfortunately I do not have anymore a development environment on Windows to make the build :-/ But no problem, even if we do not have all the versions available, we can still release the new version and if somebody is willing to contribute, can add the missing versions. I see more important right now having a working version after 9 years more than covering all the OS and cpu architectures :-) 
If you can attach the versions you have compiled here would be great so I can publish a new release for download. Thanks again!!!

**Comment by murtas** [comment]
> If you can attach the versions you have compiled here would be great so I can publish a new release for download.

you can find them in these commits;
* 6a182d945eae805ca09c62724f005762970db87e
* 64bc3a7a07eb3daa19054e0c42bc69a985b7a7cb

I was not able to compile it for windows yet.

**Comment by user2684** [comment]
Perfect thanks! I've published the new release on https://github.com/user2684/xcontrol/releases with the binaries available for the time being. Thanks again :-)

**Pull request merged**
